version: 2
updates:
# Maintain dependencies for your plugin
- package-ecosystem: maven
  directory: /
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: master
# Maintain dependencies for GitHub Actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly
