//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.06.12 at 04:56:28 PM EDT 
//


package com.aquarellian.genar.filter.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for filter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="filter">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;sequence>
 *           &lt;element name="include" type="{}IssueFilter"/>
 *         &lt;/sequence>
 *         &lt;sequence>
 *           &lt;element name="exclude" type="{}IssueFilter"/>
 *         &lt;/sequence>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "filter", propOrder = {
    "include",
    "exclude"
})
public class Filter {

    @XmlElement(required = true)
    protected IssueFilter include;
    @XmlElement(required = true)
    protected IssueFilter exclude;

    /**
     * Gets the value of the include property.
     * 
     * @return
     *     possible object is
     *     {@link IssueFilter }
     *     
     */
    public IssueFilter getInclude() {
        return include;
    }

    /**
     * Sets the value of the include property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueFilter }
     *     
     */
    public void setInclude(IssueFilter value) {
        this.include = value;
    }

    public boolean isSetInclude() {
        return (this.include!= null);
    }

    /**
     * Gets the value of the exclude property.
     * 
     * @return
     *     possible object is
     *     {@link IssueFilter }
     *     
     */
    public IssueFilter getExclude() {
        return exclude;
    }

    /**
     * Sets the value of the exclude property.
     * 
     * @param value
     *     allowed object is
     *     {@link IssueFilter }
     *     
     */
    public void setExclude(IssueFilter value) {
        this.exclude = value;
    }

    public boolean isSetExclude() {
        return (this.exclude!= null);
    }

}
